name: "gopack: build and package golang projects"
description: "Builds and packages a golang project, outputting the binaries for multiple platforms."
author: "Henry Hale"
branding:
  icon: box
  color: yellow
inputs:
  name:
    description: "Name of the project"
    required: true
  path:
    description: "Path to the golang project (relative to the repository root)."
    required: false
    default: "."
  dest:
    description: "Directory where the built files will be placed."
    required: false
    default: "./dist"
  ldflags:
    description: "Value to -ldflags build option."
    required: false
    default: "-s -w"
  flags:
    description: "Flags to pass to 'go build' command."
    required: false
    default: ""
  checksum:
    description: "A file to contain checksums for all binaries."
    required: false
    default: "checksums.txt"
  includeVersion:
    description: "Whether to add current tag or commit in release name."
    required: false
    default: "false"

runs:
  using: "node20"
  main: "./dist/index.js"
